name: build

on:
  push:
    branches: [forked]
  pull_request:
    branches: [forked]
  workflow_dispatch:

env:
  SQLITE_RELEASE_YEAR: "2021"
  SQLITE_VERSION: "3360000"

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
          - os: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Download SQLite sources
        shell: bash
        run: |
          make prepare-dist
          make download-sqlite

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo curl -L https://github.com/mindreframer/sqlite/releases/download/0.7.1-3360/sqlite3-ubuntu --output /usr/local/bin/sqlite3
          sudo chmod +x /usr/local/bin/sqlite3
          sudo apt install nodejs yarn
          sudo npm install --global yarn
          make compile-linux
          pushd testrunner && yarn install && popd
          bin/test.sh CI

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: make compile-windows

      - name: Build for Windows 2019
        if: matrix.os == 'windows-2019'
        shell: bash
        run: make compile-windows-32

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: make compile-macos
