name: publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  SQLITE_RELEASE_YEAR: "2021"
  SQLITE_VERSION: "3360000"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
          - os: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Download SQLite sources
        shell: bash
        run: |
          make prepare-dist
          make download-sqlite

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: make compile-linux

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: make compile-windows

      - name: Build for Windows
        if: matrix.os == 'windows-2019'
        shell: bash
        run: make compile-windows-32

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: make compile-macos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
